version: "3"

services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME_INSIDE=INSIDE
      - KAFKA_LISTENER_NAME_OUTSIDE=OUTSIDE
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_LISTENER_INTERNAL_HOST=kafka
      - KAFKA_LISTENER_INTERNAL_PORT=9093
      - KAFKA_BROKER_ID=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    ports:
      - "9093:9093"  # External port for INSIDE listener
      - "9092:9092"  # External port for OUTSIDE listener
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:9093  # Connect to Kafka inside network
    ports:
      - "9000:9000"  # Kafdrop UI port
    depends_on:
      - kafka
    networks:
      - kafka-net
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

networks:
  kafka-net:
    driver: bridge
